/**
 *   bun run db:types            # regenerate src/db-types.ts
 *   bun run db:types --verify   # exit 1 if it is out of date
 */
import { $ } from "bun";
import postgres from "postgres";

const OUT = "src/db-types.ts";
const serverUrl = process.env.TEST_DATABASE_URL ?? "postgres://hcai:hcai@localhost:55432/postgres";
const urlFor = (database: string) => {
  const url = new URL(serverUrl);
  url.pathname = `/${database}`;
  return url.toString();
};

/** What the `postgres` driver returns for each type with its default parsers. */
const scalar = (udt: string) => {
  if (udt === "bool") return "boolean";
  if (["int2", "int4", "oid", "float4", "float8"].includes(udt)) return "number";
  if (["timestamptz", "timestamp", "date"].includes(udt)) return "Date";
  if (["json", "jsonb"].includes(udt)) return "JsonValue";
  if (udt === "bytea") return "Buffer";
  // int8 and numeric come back as strings, like text and uuid.
  return "string";
};

type Column = { table_name: string; column_name: string; udt_name: string; is_nullable: "YES" | "NO" };

const render = (columns: Column[]) => {
  const tables = Map.groupBy(columns, (column) => column.table_name);
  const lines = [
    "// Generated by `bun run db:types` from migrations/postgres; do not edit.",
    "",
    "export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };",
    "",
    "export type Tables = {",
  ];
  for (const [table, tableColumns] of tables) {
    lines.push(`  ${table}: {`);
    for (const column of tableColumns) {
      const array = column.udt_name.startsWith("_");
      const type = scalar(array ? column.udt_name.slice(1) : column.udt_name);
      const nullable = column.is_nullable === "YES" ? " | null" : "";
      lines.push(`    ${column.column_name}: ${array ? `${type}[]` : type}${nullable};`);
    }
    lines.push("  };");
  }
  lines.push("};", "");
  return lines.join("\n");
};

const name = `hcai_types_${crypto.randomUUID().slice(0, 8)}`;
const admin = postgres(urlFor("postgres"), { max: 1, onnotice: () => {} });
await admin`CREATE DATABASE ${admin(name)}`;
try {
  await $`bun scripts/migrate.ts --only=postgres`.env({ ...process.env, DATABASE_URL: urlFor(name) }).quiet();
  const scratch = postgres(urlFor(name), { max: 1, onnotice: () => {} });
  const columns = await scratch<Column[]>`
    SELECT table_name, column_name, udt_name, is_nullable
    FROM information_schema.columns
    WHERE table_schema = 'public' AND table_name <> 'schema_migrations'
    ORDER BY table_name, ordinal_position
  `;
  await scratch.end();

  const source = render(columns);
  if (process.argv.includes("--verify")) {
    const current = await Bun.file(OUT).text().catch(() => "");
    if (current !== source) {
      console.error(`${OUT} is out of date; run bun run db:types`);
      process.exitCode = 1;
    }
  } else {
    await Bun.write(OUT, source);
  }
} finally {
  await admin`DROP DATABASE IF EXISTS ${admin(name)} WITH (FORCE)`;
  await admin.end();
}
