// Generated by `bun run db:types` from migrations/postgres; do not edit.

export type JsonValue = string | number | boolean | null | JsonValue[] | { [key: string]: JsonValue };

export type Tables = {
  abuse_events: {
    id: string;
    occurred_at: Date;
    user_id: string;
    api_key_id: string | null;
    endpoint: string;
    kind: string;
    rule: string;
    enforced: boolean;
    toolset_fingerprint: string | null;
    ip: string;
    user_agent: string;
  };
  api_keys: {
    id: string;
    user_id: string;
    key_hash: Buffer;
    key_prefix: string;
    name: string;
    created_at: Date;
    last_used_at: Date | null;
    revoked_at: Date | null;
  };
  billing_accounts: {
    id: string;
    owner_type: string;
    owner_id: string;
    status: string;
    currency: string;
    created_at: Date;
    updated_at: Date;
  };
  billing_admin_events: {
    id: string;
    account_id: string;
    actor_id: string;
    event_type: string;
    reason: string;
    details: JsonValue;
    created_at: Date;
  };
  billing_credit_grants: {
    id: string;
    account_id: string;
    source: string;
    description: string | null;
    granted_usd: string;
    reserved_usd: string;
    committed_usd: string;
    priority: number;
    valid_from: Date;
    expires_at: Date | null;
    metadata: JsonValue;
    created_at: Date;
    updated_at: Date;
  };
  billing_funding_policies: {
    id: string;
    account_id: string;
    name: string;
    cadence: string;
    timezone: string;
    amount_usd: string;
    priority: number;
    generation: number;
    effective_from: Date;
    effective_until: Date | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
  };
  billing_funding_windows: {
    id: string;
    policy_id: string;
    account_id: string;
    generation: number;
    window_start: Date;
    window_end: Date;
    granted_usd: string;
    reserved_usd: string;
    committed_usd: string;
    superseded_at: Date | null;
    created_at: Date;
    updated_at: Date;
  };
  billing_ledger_entries: {
    id: string;
    idempotency_key: string;
    account_id: string;
    reservation_id: string | null;
    direction: string;
    category: string;
    amount_usd: string;
    reason: string | null;
    metadata: JsonValue;
    effective_at: Date;
    created_at: Date;
  };
  billing_limit_policies: {
    id: string;
    account_id: string;
    name: string;
    cadence: string;
    timezone: string;
    limit_usd: string;
    generation: number;
    effective_from: Date;
    effective_until: Date | null;
    enabled: boolean;
    created_at: Date;
    updated_at: Date;
  };
  billing_limit_windows: {
    id: string;
    policy_id: string;
    account_id: string;
    generation: number;
    window_start: Date;
    window_end: Date;
    limit_usd: string;
    reserved_usd: string;
    committed_usd: string;
    overage_usd: string | null;
    superseded_at: Date | null;
    created_at: Date;
    updated_at: Date;
  };
  billing_reservation_credit_holds: {
    reservation_id: string;
    credit_grant_id: string;
    reserved_usd: string;
    committed_usd: string;
  };
  billing_reservation_funding_holds: {
    reservation_id: string;
    funding_window_id: string;
    reserved_usd: string;
    committed_usd: string;
  };
  billing_reservation_limit_holds: {
    reservation_id: string;
    limit_window_id: string;
    reserved_usd: string;
    committed_usd: string;
  };
  billing_reservations: {
    id: string;
    request_id: string;
    account_id: string;
    provider: string;
    provider_request_id: string | null;
    state: string;
    estimated_cost_usd: string;
    actual_cost_usd: string | null;
    unfunded_cost_usd: string;
    usage_source: string | null;
    reconciliation_reason: string | null;
    expires_at: Date;
    created_at: Date;
    updated_at: Date;
    finalized_at: Date | null;
    user_id: string | null;
    api_key_id: string | null;
    endpoint: string | null;
    pending_since: Date | null;
  };
  replicate_resources: {
    kind: string;
    id: string;
    user_id: string;
    api_key_id: string | null;
    model: string | null;
    created_at: Date;
  };
  request_event_outbox: {
    id: string;
    payload: JsonValue;
    attempts: number;
    last_error: string | null;
    created_at: Date;
    claimed_at: Date | null;
  };
  sessions: {
    id: string;
    user_id: string;
    token_hash: Buffer;
    expires_at: Date;
    created_at: Date;
  };
  users: {
    id: string;
    slack_id: string;
    email: string | null;
    name: string | null;
    avatar: string | null;
    is_banned: boolean;
    is_idv_verified: boolean;
    skip_idv: boolean;
    created_at: Date;
    updated_at: Date;
    agent_banner_dismissed_at: Date | null;
  };
};
